name: Lint & Format

on: [pull_request]

jobs:

  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15']
    name: Linting and Formatting Node ${{ matrix.node }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run lint and Prettier check
        run: npm run lint && npm run format:check