name: Lint and Prettier Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint 
        run: node_modules/.bin/eslint . --fix || echo 'Linting completed with auto-fixes'
      
      - name: Prettier Format
        run: node_modules/.bin/prettier --write .      
         
